### PR TITLE
BLIlluminationDiscriminationCalcs json

### PR DESCRIPTION
**Pull request by xnieamo**
Is forking and then making a pull request the best way to do this if I don't have permissions to the repository? 

Should I manually delete my fork after the pull request is accepted?

Xiaomao

### CODE REVIEW

**Comment by benjamin-heasly** [comment]
I think fork/pull request is a great way!  I think we can delete the branch from here in the PR when we do the merge.

Can I suggest a change?  Since some of the toolboxes you declared are already known to the registry, I think you should include the JSON from the registry instead of declaring fresh git configuration in the JSON here.

That way, if the installation process changes for a toolbox in the registry, you won't have to update the JSON here to match it.  I think isetbio is one project where the installation may change.

The JSON syntax to include isetbio from the registry would be:
```
		"flavor": "",
		"hook": "",
		"importance": "",
		"localHookTemplate": "",
		"name": "isetbio",
		"pathPlacement": "append",
		"subfolder": "",
		"toolboxRoot": "",
		"type": "include",
		"update": "",
		"url": ""
```

And similar for UnitTestToolbox and RemoteDataToolbox.

What do you think?

**Comment by xnieamo** [comment]
That seems like a good idea. I've made these changes to the JSON in my fork. It seems like my commit/push is getting tracked in this thread, so I'm guessing this means I don't need to make a new pull request?

**Comment by benjamin-heasly** [comment]
Looks good to me! :+1: 

Thanks for the PR.

**Comment by benjamin-heasly** [comment]
Now that it's merged, does it give you a button to delete the fork?

**Comment by xnieamo** [comment]
It doesn't seem to automatically detect the merge.  I've gone ahead and deleted my fork like a normal repository via settings.  Everything seems to be working fine though, so I'll close this thread.

**Pull request merged**
